import { create } from 'zustand';
import { translate as apiTranslate, API_BASE_URL } from '../api/client';
import { DEMO_SAMPLES } from '../demo/samples';

export type TranslationMode = 
  | 'auto'
  | 'natural'
  | 'literary'
  | 'academic'
  | 'business'
  | 'comic';

export type InputMode = 'text' | 'image';

// Where the current image came from. Demo images are fixed sample content
// (no remove/replace affordances); user images are real uploads.
export type ImageSource = 'demo' | 'user' | null;

// Pure UI state for the image lightbox. Never touches input/result data.
export interface PreviewImage {
  src: string;
  alt: string;
}

export type TranslationSegmentType =
  | 'dialogue'
  | 'narration'
  | 'sound_effect'
  | 'title'
  | 'ui_text'
  | 'sign'
  | 'caption'
  | 'text';

export interface TranslationSegment {
  type: TranslationSegmentType;
  source: string;
  translation: string;
}

export interface TranslationNote {
  source: string;
  translation: string;
  reason: string;
}

export interface TranslationResult {
  sourceLanguage: string;
  targetLanguage: string;
  translation: string;
  detectedText?: string;
  segments: TranslationSegment[];
  notes: TranslationNote[];
  // Distinguishes demo sample data from a real model response so rendering
  // and actions (copy/regenerate/export) can tell the two apart.
  source?: 'demo' | 'real';
}

interface TranslationState {
  // Input
  inputText: string;
  inputImage: string | null;
  inputMode: InputMode;
  imageSource: ImageSource;

  // Lightbox (pure UI; rendered by <Lightbox /> at the app root)
  previewImage: PreviewImage | null;
  
  // Settings
  mode: TranslationMode;
  context: string;
  terminology: string;
  preserveNames: boolean;
  explainTranslation: boolean;
  // Display-only toggle: notes are always generated by the model; this only
  // controls whether the UI shows them. Persisted across translations.
  showTranslationNotes: boolean;
  
  // Result
  result: TranslationResult | null;
  isLoading: boolean;
  error: string | null;
  
  // Explicit demo state. Demo data may only be shown while this is true;
  // any real user action (editing, real image, translating) flips it off.
  isDemoMode: boolean;
  // Guards against a slow image fetch overwriting a newer sample/action.
  activeDemoId: string | null;
  
  // Service status
  isServiceOnline: boolean;
  
  // Actions
  setInputText: (text: string) => void;
  setInputImage: (image: string | null) => void;
  setInputMode: (mode: InputMode) => void;
  openPreview: (src: string, alt: string) => void;
  closePreview: () => void;
  setMode: (mode: TranslationMode) => void;
  setContext: (context: string) => void;
  setTerminology: (terminology: string) => void;
  setPreserveNames: (preserve: boolean) => void;
  setExplainTranslation: (explain: boolean) => void;
  toggleShowTranslationNotes: () => void;
  setResult: (result: TranslationResult | null) => void;
  setIsLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  setServiceOnline: (online: boolean) => void;
  checkService: () => Promise<void>;
  loadDemoSample: (index: number) => Promise<void>;
  translate: () => Promise<void>;
  reset: () => void;
}

export const useTranslationStore = create<TranslationState>((set, get) => ({
  inputText: '',
  inputImage: null,
  inputMode: 'text',
  imageSource: null,
  previewImage: null,
  
  mode: 'auto',
  context: '',
  terminology: '',
  preserveNames: true,
  explainTranslation: true,
  showTranslationNotes: false,
  
  result: null,
  isLoading: false,
  error: null,
  isDemoMode: false,
  activeDemoId: null,
  isServiceOnline: true,
  
  // Any real user action immediately exits demo mode and drops demo data.
  // loadDemoSample bypasses these setters on purpose: it performs one full
  // state replacement so no real data can leak into (or out of) the demo.
  setInputText: (text) => set((s) => (
    s.isDemoMode
      ? { inputText: text, isDemoMode: false, activeDemoId: null, result: null, error: null }
      : { inputText: text }
  )),
  // A non-null image is always a real upload here (demo images are attached
  // directly inside loadDemoSample). Any image change closes the lightbox so
  // a stale preview can never outlive the image it showed.
  setInputImage: (image) => set((s) => {
    if (image && s.isDemoMode) {
      return { inputImage: image, imageSource: 'user', isDemoMode: false, activeDemoId: null, result: null, error: null, previewImage: null };
    }
    if (!image) {
      return { inputImage: null, imageSource: null, previewImage: null };
    }
    return { inputImage: image, imageSource: 'user', previewImage: null };
  }),
  setInputMode: (mode) => set({ inputMode: mode }),
  openPreview: (src, alt) => set({ previewImage: { src, alt } }),
  closePreview: () => set({ previewImage: null }),
  setMode: (mode) => set({ mode }),
  setContext: (context) => set({ context }),
  setTerminology: (terminology) => set({ terminology }),
  setPreserveNames: (preserve) => set({ preserveNames: preserve }),
  setExplainTranslation: (explain) => set({ explainTranslation: explain }),
  toggleShowTranslationNotes: () => set((s) => ({ showTranslationNotes: !s.showTranslationNotes })),
  setResult: (result) => set({ result }),
  setIsLoading: (loading) => set({ isLoading: loading }),
  setError: (error) => set({ error }),
  setServiceOnline: (online) => set({ isServiceOnline: online }),
  checkService: async () => {
    try {
      const response = await fetch(`${API_BASE_URL}/translate`, { method: 'OPTIONS' });
      set({ isServiceOnline: response.ok });
    } catch {
      set({ isServiceOnline: false });
    }
  },
  
  // Full demo-state replacement: clears ALL real data, loads the sample
  // (including mode/context/terminology), and marks the state explicitly
  // as demo. Image samples fetch their file and attach the data URL, with
  // a sample-id guard so a slow fetch cannot clobber a newer selection.
  loadDemoSample: async (index) => {
    const demo = DEMO_SAMPLES[index];
    if (!demo) return;

    set({
      inputText: demo.inputType === 'text' ? demo.source : '',
      inputImage: null,
      inputMode: demo.inputType,
      imageSource: demo.inputType === 'image' ? 'demo' : null,
      mode: demo.mode,
      context: demo.context ?? '',
      terminology: demo.terminology ?? '',
      preserveNames: demo.preserveProperNames ?? true,
      result: { ...demo.result, source: 'demo' },
      isLoading: false,
      error: null,
      isDemoMode: true,
      activeDemoId: demo.id,
      previewImage: null,
    });

    if (demo.inputType === 'image' && demo.demoImage) {
      try {
        const response = await fetch(demo.demoImage);
        const blob = await response.blob();
        const dataUrl = await new Promise<string>((resolve, reject) => {
          const reader = new FileReader();
          reader.onload = () => resolve(reader.result as string);
          reader.onerror = () => reject(reader.error);
          reader.readAsDataURL(blob);
        });
        // Apply only if the same sample is still active and still demo.
        const current = get();
        if (current.isDemoMode && current.activeDemoId === demo.id) {
          set({ inputImage: dataUrl });
        }
      } catch {
        // Demo image is optional decoration; real flow is unaffected.
      }
    }
  },
  
  translate: async () => {
    const state = get();
    if (!state.inputText.trim() && !state.inputImage) return;
    
    // Translating is a real action: exit demo and drop any demo result.
    // A demo image being translated has been adopted as real content, so it
    // becomes a user image (full remove/replace affordances from now on).
    set({
      isLoading: true,
      error: null,
      isDemoMode: false,
      activeDemoId: null,
      result: null,
      imageSource: state.imageSource === 'demo' ? 'user' : state.imageSource,
    });
    
    try {
      const response = await apiTranslate({
        text: state.inputText || undefined,
        imageDataUrl: state.inputImage || undefined,
        mode: state.mode,
        context: state.context || undefined,
        terminology: state.terminology || undefined,
        preserveNames: state.preserveNames,
        explainTranslation: state.explainTranslation
      });
      
      set({
        result: {
          source: 'real',
          sourceLanguage: response.source_language,
          targetLanguage: response.target_language,
          translation: response.translation,
          detectedText: response.detected_text || undefined,
          segments: (response.segments || []).map(s => ({
            ...s,
            type: s.type as TranslationSegmentType
          })),
          notes: response.notes || []
        },
        isLoading: false
      });
    } catch (err) {
      set({
        isLoading: false,
        error: err instanceof Error ? err.message : '翻译服务暂时不可用，请稍后重试'
      });
    }
  },
  
  reset: () => set({
    inputText: '',
    inputImage: null,
    imageSource: null,
    result: null,
    error: null,
    isDemoMode: false,
    activeDemoId: null,
    previewImage: null,
  })
}));
