import { create } from 'zustand';
import { translateStream as apiTranslateStream, checkHealth } from '../api/client';
import { DEMO_SAMPLES } from '../demo/samples';

export type TranslationMode = 
  | 'auto'
  | 'natural'
  | 'literary'
  | 'academic'
  | 'business'
  | 'comic';

export type InputMode = 'text' | 'image';

// Where the current image came from. Demo images are fixed sample content
// (no remove/replace affordances); user images are real uploads.
export type ImageSource = 'demo' | 'user' | null;

// Pure UI state for the image lightbox. Never touches input/result data.
export interface PreviewImage {
  src: string;
  alt: string;
}

export type TranslationSegmentType =
  | 'dialogue'
  | 'narration'
  | 'sound_effect'
  | 'title'
  | 'ui_text'
  | 'sign'
  | 'caption'
  | 'background_text'
  | 'text';

export interface TranslationSegment {
  type: TranslationSegmentType;
  source: string;
  translation: string;
  // Comic-mode extras (optional; plain image/text results omit them):
  // which panel the text belongs to, its global reading order, who is
  // speaking, and the model-declared reply dependency (id / reply_to).
  // The store spreads response segments, so these survive as-is.
  panel?: number;
  order?: number;
  speaker?: string | null;
  id?: string;
  reply_to?: string | null;
}

export interface TranslationNote {
  source: string;
  translation: string;
  reason: string;
}

export interface TranslationResult {
  sourceLanguage: string;
  targetLanguage: string;
  translation: string;
  detectedText?: string;
  segments: TranslationSegment[];
  notes: TranslationNote[];
  // Distinguishes demo sample data from a real model response so rendering
  // and actions (copy/regenerate/export) can tell the two apart.
  source?: 'demo' | 'real';
}

interface TranslationState {
  // Input
  inputText: string;
  inputImage: string | null;
  inputMode: InputMode;
  imageSource: ImageSource;

  // Lightbox (pure UI; rendered by <Lightbox /> at the app root)
  previewImage: PreviewImage | null;
  
  // Settings
  mode: TranslationMode;
  context: string;
  terminology: string;
  preserveNames: boolean;
  explainTranslation: boolean;
  // Display-only toggle: notes are always generated by the model; this only
  // controls whether the UI shows them. Persisted across translations.
  showTranslationNotes: boolean;
  
  // Result
  result: TranslationResult | null;
  isLoading: boolean;
  error: string | null;
  // Streaming provisional state (see translate() for the lifecycle).
  streamingText: string;
  isStreaming: boolean;
  streamStatus: string | null;
  
  // Explicit demo state. Demo data may only be shown while this is true;
  // any real user action (editing, real image, translating) flips it off.
  isDemoMode: boolean;
  // Guards against a slow image fetch overwriting a newer sample/action.
  activeDemoId: string | null;
  
  // Service status
  isServiceOnline: boolean;
  
  // Actions
  setInputText: (text: string) => void;
  setInputImage: (image: string | null) => void;
  setInputMode: (mode: InputMode) => void;
  openPreview: (src: string, alt: string) => void;
  closePreview: () => void;
  setMode: (mode: TranslationMode) => void;
  setContext: (context: string) => void;
  setTerminology: (terminology: string) => void;
  setPreserveNames: (preserve: boolean) => void;
  setExplainTranslation: (explain: boolean) => void;
  toggleShowTranslationNotes: () => void;
  setResult: (result: TranslationResult | null) => void;
  setIsLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  setServiceOnline: (online: boolean) => void;
  checkService: () => Promise<void>;
  loadDemoSample: (index: number) => Promise<void>;
  translate: () => Promise<void>;
  reset: () => void;
}

// Streaming request lifecycle (module-level, not serializable state):
// a new translate()/reset()/demo switch aborts any in-flight stream so stale
// chunks can never pollute a newer session.
let activeAbort: AbortController | null = null;
let requestGeneration = 0;

function abortActiveStream() {
  if (activeAbort) {
    activeAbort.abort();
    activeAbort = null;
  }
}

export const useTranslationStore = create<TranslationState>((set, get) => ({
  inputText: '',
  inputImage: null,
  inputMode: 'text',
  imageSource: null,
  previewImage: null,
  
  mode: 'auto',
  context: '',
  terminology: '',
  preserveNames: true,
  explainTranslation: true,
  showTranslationNotes: false,
  
  result: null,
  isLoading: false,
  error: null,
  // Streaming provisional state. streamingText is NOT the canonical result:
  // it only feeds the ResultArea provisional view until the final event
  // replaces it wholesale.
  streamingText: '',
  isStreaming: false,
  streamStatus: null,
  isDemoMode: false,
  activeDemoId: null,
  isServiceOnline: true,
  
  // Any real user action immediately exits demo mode and drops demo data.
  // loadDemoSample bypasses these setters on purpose: it performs one full
  // state replacement so no real data can leak into (or out of) the demo.
  setInputText: (text) => set((s) => (
    s.isDemoMode
      ? { inputText: text, isDemoMode: false, activeDemoId: null, result: null, error: null }
      : { inputText: text }
  )),
  // A non-null image is always a real upload here (demo images are attached
  // directly inside loadDemoSample). Any image change closes the lightbox so
  // a stale preview can never outlive the image it showed.
  setInputImage: (image) => set((s) => {
    if (image && s.isDemoMode) {
      return { inputImage: image, imageSource: 'user', isDemoMode: false, activeDemoId: null, result: null, error: null, previewImage: null };
    }
    if (!image) {
      return { inputImage: null, imageSource: null, previewImage: null };
    }
    return { inputImage: image, imageSource: 'user', previewImage: null };
  }),
  setInputMode: (mode) => set({ inputMode: mode }),
  openPreview: (src, alt) => set({ previewImage: { src, alt } }),
  closePreview: () => set({ previewImage: null }),
  setMode: (mode) => set({ mode }),
  setContext: (context) => set({ context }),
  setTerminology: (terminology) => set({ terminology }),
  setPreserveNames: (preserve) => set({ preserveNames: preserve }),
  setExplainTranslation: (explain) => set({ explainTranslation: explain }),
  toggleShowTranslationNotes: () => set((s) => ({ showTranslationNotes: !s.showTranslationNotes })),
  setResult: (result) => set({ result }),
  setIsLoading: (loading) => set({ isLoading: loading }),
  setError: (error) => set({ error }),
  setServiceOnline: (online) => set({ isServiceOnline: online }),
  checkService: async () => {
    set({ isServiceOnline: await checkHealth() });
  },
  
  // Full demo-state replacement: clears ALL real data, loads the sample
  // (including mode/context/terminology), and marks the state explicitly
  // as demo. Image samples fetch their file and attach the data URL, with
  // a sample-id guard so a slow fetch cannot clobber a newer selection.
  loadDemoSample: async (index) => {
    const demo = DEMO_SAMPLES[index];
    if (!demo) return;

    // Switching to a demo voids any in-flight real translation.
    abortActiveStream();

    set({
      inputText: demo.inputType === 'text' ? demo.source : '',
      inputImage: null,
      inputMode: demo.inputType,
      imageSource: demo.inputType === 'image' ? 'demo' : null,
      mode: demo.mode,
      context: demo.context ?? '',
      terminology: demo.terminology ?? '',
      preserveNames: demo.preserveProperNames ?? true,
      result: { ...demo.result, source: 'demo' },
      isLoading: false,
      error: null,
      isDemoMode: true,
      activeDemoId: demo.id,
      previewImage: null,
      isStreaming: false,
      streamingText: '',
      streamStatus: null,
    });

    if (demo.inputType === 'image' && demo.demoImage) {
      try {
        const response = await fetch(demo.demoImage);
        const blob = await response.blob();
        const dataUrl = await new Promise<string>((resolve, reject) => {
          const reader = new FileReader();
          reader.onload = () => resolve(reader.result as string);
          reader.onerror = () => reject(reader.error);
          reader.readAsDataURL(blob);
        });
        // Apply only if the same sample is still active and still demo.
        const current = get();
        if (current.isDemoMode && current.activeDemoId === demo.id) {
          set({ inputImage: dataUrl });
        }
      } catch {
        // Demo image is optional decoration; real flow is unaffected.
      }
    }
  },
  
  translate: async () => {
    const state = get();
    if (!state.inputText.trim() && !state.inputImage) return;
    
    // Translating is a real action: exit demo and drop any demo result.
    // A demo image being translated has been adopted as real content, so it
    // becomes a user image (full remove/replace affordances from now on).
    abortActiveStream();
    const generation = ++requestGeneration;
    const controller = new AbortController();
    activeAbort = controller;

    set({
      isLoading: true,
      error: null,
      isDemoMode: false,
      activeDemoId: null,
      result: null,
      imageSource: state.imageSource === 'demo' ? 'user' : state.imageSource,
      streamingText: '',
      isStreaming: true,
      // Comic streams no translation text (final is rebuilt from segments);
      // surface what the backend is doing instead.
      streamStatus: state.mode === 'comic' ? '正在分析漫画结构…' : null,
    });
    
    try {
      const response = await apiTranslateStream({
        text: state.inputText || undefined,
        imageDataUrl: state.inputImage || undefined,
        mode: state.mode,
        context: state.context || undefined,
        terminology: state.terminology || undefined,
        preserveNames: state.preserveNames,
        explainTranslation: state.explainTranslation
      }, {
        onDelta: (text) => {
          if (generation !== requestGeneration || controller.signal.aborted) return;
          set((s) => ({ streamingText: s.streamingText + text }));
        },
        onReset: () => {
          if (generation !== requestGeneration || controller.signal.aborted) return;
          set({
            streamingText: '',
            streamStatus: '译文较长，正在重新生成完整结果…',
          });
        },
      }, controller.signal);

      // A newer session started meanwhile: this result is stale.
      if (generation !== requestGeneration) return;

      set({
        result: {
          source: 'real',
          sourceLanguage: response.source_language,
          targetLanguage: response.target_language,
          translation: response.translation,
          detectedText: response.detected_text || undefined,
          segments: (response.segments || []).map(s => ({
            ...s,
            type: s.type as TranslationSegmentType
          })),
          notes: response.notes || []
        },
        isLoading: false,
        isStreaming: false,
        streamingText: '',
        streamStatus: null,
      });
    } catch (err) {
      if (generation !== requestGeneration) return;
      set({
        isLoading: false,
        isStreaming: false,
        streamingText: '',
        streamStatus: null,
        error: err instanceof Error ? err.message : '翻译服务暂时不可用，请稍后重试'
      });
    } finally {
      if (activeAbort === controller) activeAbort = null;
    }
  },
  
  // Full new-session reset (single implementation behind every "新建翻译"
  // entry). Clears the whole translation session: input, image, settings
  // (incl. anything a demo sample filled in), result/notes and demo state.
  // Deliberately KEEPS global app state: theme, service status.
  reset: () => {
    abortActiveStream();
    set({
      inputText: '',
      inputImage: null,
      inputMode: 'text',
      imageSource: null,
      mode: 'auto',
      context: '',
      terminology: '',
      preserveNames: true,
      showTranslationNotes: false,
      result: null,
      error: null,
      isLoading: false,
      isDemoMode: false,
      activeDemoId: null,
      previewImage: null,
      isStreaming: false,
      streamingText: '',
      streamStatus: null,
    });
  }
}));
