import { create } from 'zustand';
import { translateStream as apiTranslateStream, checkHealth, type TranslationResponse } from '../api/client';
import { DEMO_SAMPLES } from '../demo/samples';
import { translateDocument, type DocumentProgressStatus } from '../services/document/translateDocument';
import { translatePdfAsImages, type PdfVisionStatus } from '../services/document/pdfVision';
import type { DocumentFileErrorCode, ParsedDocumentFile } from '../services/document/fileParser';

export type TranslationMode = 
  | 'auto'
  | 'natural'
  | 'literary'
  | 'academic'
  | 'business'
  | 'comic';

export type InputMode = 'text' | 'image' | 'file';

// Where the current image came from. Demo images are fixed sample content
// (no remove/replace affordances); user images are real uploads.
export type ImageSource = 'demo' | 'user' | null;

// Pure UI state for the image lightbox. Never touches input/result data.
export interface PreviewImage {
  src: string;
  alt: string;
}

export type TranslationSegmentType =
  | 'dialogue'
  | 'narration'
  | 'sound_effect'
  | 'title'
  | 'ui_text'
  | 'sign'
  | 'caption'
  | 'background_text'
  | 'text';

export interface TranslationSegment {
  type: TranslationSegmentType;
  source: string;
  translation: string;
  // Comic-mode extras (optional; plain image/text results omit them):
  // which panel the text belongs to, its global reading order, who is
  // speaking, and the model-declared reply dependency (id / reply_to).
  // The store spreads response segments, so these survive as-is.
  panel?: number;
  order?: number;
  speaker?: string | null;
  id?: string;
  reply_to?: string | null;
}

export interface TranslationNote {
  source: string;
  translation: string;
  reason: string;
}

export interface TranslationResult {
  sourceLanguage: string;
  targetLanguage: string;
  translation: string;
  detectedText?: string;
  segments: TranslationSegment[];
  notes: TranslationNote[];
  // Distinguishes demo sample data from a real model response so rendering
  // and actions (copy/regenerate/export) can tell the two apart.
  source?: 'demo' | 'real';
}

interface TranslationState {
  // Input. There is no stored input mode: the pipeline is derived from what is
  // attached (see effectiveInputMode).
  inputText: string;
  inputImage: string | null;
  imageSource: ImageSource;
  documentFile: ParsedDocumentFile | null;
  fileStatus: 'idle' | 'parsing' | 'ready' | 'error';
  fileError: string | null;
  // Reason the file was rejected, so the UI can offer the vision route for a
  // PDF that has no usable text layer.
  fileErrorCode: DocumentFileErrorCode | null;
  // The raw file, kept for routes that need to read it again (page rendering).
  documentSourceFile: File | null;

  // Lightbox (pure UI; rendered by <Lightbox /> at the app root)
  previewImage: PreviewImage | null;
  
  // Settings
  mode: TranslationMode;
  context: string;
  terminology: string;
  preserveNames: boolean;
  explainTranslation: boolean;
  // Display-only toggle: notes are always generated by the model; this only
  // controls whether the UI shows them. Persisted across translations.
  showTranslationNotes: boolean;
  
  // Result
  result: TranslationResult | null;
  isLoading: boolean;
  error: string | null;
  // Streaming provisional state (see translate() for the lifecycle).
  streamingText: string;
  isStreaming: boolean;
  streamStatus: string | null;
  progressPercent: number | null;
  
  // Explicit demo state. Demo data may only be shown while this is true;
  // any real user action (editing, real image, translating) flips it off.
  isDemoMode: boolean;
  // Guards against a slow image fetch overwriting a newer sample/action.
  activeDemoId: string | null;
  
  // Service status
  isServiceOnline: boolean;
  
  // Actions
  setInputText: (text: string) => void;
  setInputImage: (image: string | null) => void;
  setDocumentFile: (file: ParsedDocumentFile | null) => void;
  setDocumentSourceFile: (file: File | null) => void;
  setFileStatus: (status: TranslationState['fileStatus'], error?: string | null, code?: DocumentFileErrorCode | null) => void;
  openPreview: (src: string, alt: string) => void;
  closePreview: () => void;
  setMode: (mode: TranslationMode) => void;
  setContext: (context: string) => void;
  setTerminology: (terminology: string) => void;
  setPreserveNames: (preserve: boolean) => void;
  setExplainTranslation: (explain: boolean) => void;
  toggleShowTranslationNotes: () => void;
  setResult: (result: TranslationResult | null) => void;
  setIsLoading: (loading: boolean) => void;
  setError: (error: string | null) => void;
  setServiceOnline: (online: boolean) => void;
  checkService: () => Promise<void>;
  loadDemoSample: (index: number) => Promise<void>;
  translate: () => Promise<void>;
  translateScannedPdf: () => Promise<void>;
  reset: () => void;
}

// Streaming request lifecycle (module-level, not serializable state):
// a new translate()/reset()/demo switch aborts any in-flight stream so stale
// chunks can never pollute a newer session.
let activeAbort: AbortController | null = null;
let requestGeneration = 0;

function invalidateActiveStream() {
  requestGeneration += 1;
  if (activeAbort) {
    activeAbort.abort();
    activeAbort = null;
  }
}

// The upload entry is unified: there is no user-visible mode switch any more, so
// the pipeline follows what is actually attached. Deriving it here (instead of
// storing a mode the UI must remember to reset) makes a stale mode impossible:
// removing an attachment returns the session to plain text automatically.
export function effectiveInputMode(input: Pick<TranslationState, 'documentFile' | 'inputImage'>): InputMode {
  if (input.documentFile) return 'file';
  if (input.inputImage) return 'image';
  return 'text';
}

// Single mapping from a model response to the session result, shared by the
// text/document/vision paths so their result shape cannot drift apart.
function toTranslationResult(response: TranslationResponse): TranslationResult {
  return {
    source: 'real',
    sourceLanguage: response.source_language,
    targetLanguage: response.target_language,
    translation: response.translation,
    detectedText: response.detected_text || undefined,
    segments: (response.segments || []).map((segment) => ({
      ...segment,
      type: segment.type as TranslationSegmentType,
    })),
    notes: response.notes || [],
  };
}

function visionStatusText(status: PdfVisionStatus, percent: number): string {
  if (status === 'rendering') return '正在渲染 PDF 页面…';
  if (status === 'assembling') return '正在整理完整译文…';
  return `正在逐页识别翻译… 已完成 ${percent}%`;
}

export const useTranslationStore = create<TranslationState>((set, get) => ({
  inputText: '',
  inputImage: null,
  imageSource: null,
  documentFile: null,
  fileStatus: 'idle',
  fileError: null,
  fileErrorCode: null,
  documentSourceFile: null,
  previewImage: null,
  
  mode: 'auto',
  context: '',
  terminology: '',
  preserveNames: true,
  explainTranslation: true,
  showTranslationNotes: false,
  
  result: null,
  isLoading: false,
  error: null,
  // Streaming provisional state. streamingText is NOT the canonical result:
  // it only feeds the ResultArea provisional view until the final event
  // replaces it wholesale.
  streamingText: '',
  isStreaming: false,
  streamStatus: null,
  progressPercent: null,
  isDemoMode: false,
  activeDemoId: null,
  isServiceOnline: true,
  
  // Any real user action immediately exits demo mode and drops demo data.
  // loadDemoSample bypasses these setters on purpose: it performs one full
  // state replacement so no real data can leak into (or out of) the demo.
  setInputText: (text) => set((s) => (
    s.isDemoMode
      ? { inputText: text, isDemoMode: false, activeDemoId: null, result: null, error: null }
      : { inputText: text }
  )),
  // A non-null image is always a real upload here (demo images are attached
  // directly inside loadDemoSample). Any image change closes the lightbox so
  // a stale preview can never outlive the image it showed.
  setInputImage: (image) => set((s) => {
    if (image && s.isDemoMode) {
      return { inputImage: image, imageSource: 'user', isDemoMode: false, activeDemoId: null, result: null, error: null, previewImage: null };
    }
    if (!image) {
      return { inputImage: null, imageSource: null, previewImage: null };
    }
    return { inputImage: image, imageSource: 'user', previewImage: null };
  }),
  setDocumentFile: (file) => set({
    documentFile: file,
    fileStatus: file ? 'ready' : 'idle',
    fileError: null,
    fileErrorCode: null,
    isDemoMode: false,
    activeDemoId: null,
    result: null,
  }),
  setDocumentSourceFile: (file) => set({ documentSourceFile: file }),
  setFileStatus: (status, error = null, code = null) => set({ fileStatus: status, fileError: error, fileErrorCode: code }),
  openPreview: (src, alt) => set({ previewImage: { src, alt } }),
  closePreview: () => set({ previewImage: null }),
  setMode: (mode) => set({ mode }),
  setContext: (context) => set({ context }),
  setTerminology: (terminology) => set({ terminology }),
  setPreserveNames: (preserve) => set({ preserveNames: preserve }),
  setExplainTranslation: (explain) => set({ explainTranslation: explain }),
  toggleShowTranslationNotes: () => set((s) => ({ showTranslationNotes: !s.showTranslationNotes })),
  setResult: (result) => set({ result }),
  setIsLoading: (loading) => set({ isLoading: loading }),
  setError: (error) => set({ error }),
  setServiceOnline: (online) => set({ isServiceOnline: online }),
  checkService: async () => {
    set({ isServiceOnline: await checkHealth() });
  },
  
  // Full demo-state replacement: clears ALL real data, loads the sample
  // (including mode/context/terminology), and marks the state explicitly
  // as demo. Image samples fetch their file and attach the data URL, with
  // a sample-id guard so a slow fetch cannot clobber a newer selection.
  loadDemoSample: async (index) => {
    const demo = DEMO_SAMPLES[index];
    if (!demo) return;

    // Switching to a demo voids any in-flight real translation.
    invalidateActiveStream();

    set({
      inputText: demo.inputType === 'text' ? demo.source : '',
      inputImage: null,
      imageSource: demo.inputType === 'image' ? 'demo' : null,
      documentFile: null,
      fileStatus: 'idle',
      fileError: null,
      fileErrorCode: null,
      documentSourceFile: null,
      mode: demo.mode,
      context: demo.context ?? '',
      terminology: demo.terminology ?? '',
      preserveNames: demo.preserveProperNames ?? true,
      result: { ...demo.result, source: 'demo' },
      isLoading: false,
      error: null,
      isDemoMode: true,
      activeDemoId: demo.id,
      previewImage: null,
      isStreaming: false,
      streamingText: '',
      streamStatus: null,
      progressPercent: null,
    });

    if (demo.inputType === 'image' && demo.demoImage) {
      try {
        const response = await fetch(demo.demoImage);
        const blob = await response.blob();
        const dataUrl = await new Promise<string>((resolve, reject) => {
          const reader = new FileReader();
          reader.onload = () => resolve(reader.result as string);
          reader.onerror = () => reject(reader.error);
          reader.readAsDataURL(blob);
        });
        // Apply only if the same sample is still active and still demo.
        const current = get();
        if (current.isDemoMode && current.activeDemoId === demo.id) {
          set({ inputImage: dataUrl });
        }
      } catch {
        // Demo image is optional decoration; real flow is unaffected.
      }
    }
  },
  
  translate: async () => {
    const state = get();
    const inputMode = effectiveInputMode(state);
    const documentText = inputMode === 'file' ? state.documentFile?.text || '' : state.inputText;
    if (inputMode === 'text' && !documentText.trim()) return;
    
    // Translating is a real action: exit demo and drop any demo result.
    // A demo image being translated has been adopted as real content, so it
    // becomes a user image (full remove/replace affordances from now on).
    invalidateActiveStream();
    const generation = requestGeneration;
    const controller = new AbortController();
    activeAbort = controller;
    const isCurrent = () => generation === requestGeneration && !controller.signal.aborted;

    set({
      isLoading: true,
      error: null,
      isDemoMode: false,
      activeDemoId: null,
      result: null,
      imageSource: state.imageSource === 'demo' ? 'user' : state.imageSource,
      streamingText: '',
      isStreaming: true,
      // Comic streams no translation text (final is rebuilt from segments);
      // surface what the backend is doing instead.
      streamStatus: state.mode === 'comic' ? '正在分析漫画结构…' : null,
      progressPercent: inputMode === 'image' ? null : 0,
    });
    
    try {
      const streamHandlers = {
        onDelta: (text: string) => {
          if (!isCurrent()) return;
          set((s) => ({ streamingText: s.streamingText + text }));
        },
        onReset: (reason: string) => {
          if (!isCurrent()) return;
          set({
            streamingText: '',
            streamStatus: reason === 'stream_interrupted' || reason === 'transport_interrupted'
              ? '连接中断，正在重新连接并生成完整结果…'
              : reason === 'format_error'
                ? '结果格式异常，正在重新生成完整结果…'
                : '译文较长，正在重新生成完整结果…',
          });
        },
      };

      const statusText = (status: DocumentProgressStatus, percent: number) => {
        if (status === 'analyzing') return '正在分析长文本…';
        if (status === 'retrying-part') return '正在重新处理部分内容…';
        if (status === 'assembling') return '正在整理完整译文…';
        return `正在翻译长文内容… 已完成 ${percent}%`;
      };

      const response = inputMode === 'image'
        ? await apiTranslateStream({
            text: state.inputText || undefined,
            imageDataUrl: state.inputImage || undefined,
            mode: state.mode,
            context: state.context || undefined,
            terminology: state.terminology || undefined,
            preserveNames: state.preserveNames,
            explainTranslation: state.explainTranslation,
          }, streamHandlers, controller.signal)
        : await translateDocument({
            text: documentText,
            mode: state.mode,
            context: state.context || undefined,
            terminology: state.terminology || undefined,
            preserveNames: state.preserveNames,
            explainTranslation: state.explainTranslation,
          }, {
            signal: controller.signal,
            onProgress: ({ percent, status, provisionalText }) => {
              if (!isCurrent()) return;
              set({
                streamingText: provisionalText,
                streamStatus: statusText(status, percent),
                progressPercent: percent,
              });
            },
          });

      // A newer session started meanwhile: this result is stale.
      if (!isCurrent()) return;

      set({
        result: toTranslationResult(response),
        isLoading: false,
        isStreaming: false,
        streamingText: '',
        streamStatus: null,
        progressPercent: 100,
      });
    } catch (err) {
      if (!isCurrent()) return;
      set({
        isLoading: false,
        isStreaming: false,
        streamingText: '',
        streamStatus: null,
        progressPercent: null,
        error: err instanceof Error ? err.message : '翻译服务暂时不可用，请稍后重试'
      });
    } finally {
      if (activeAbort === controller) activeAbort = null;
    }
  },

  // Vision route for a PDF that has no usable text layer. It is always an
  // explicit user action: every page is sent as an image, which costs far more
  // than the text pipeline.
  translateScannedPdf: async () => {
    const state = get();
    const file = state.documentSourceFile;
    if (!file) return;

    invalidateActiveStream();
    const generation = requestGeneration;
    const controller = new AbortController();
    activeAbort = controller;
    const isCurrent = () => generation === requestGeneration && !controller.signal.aborted;

    set({
      isLoading: true,
      error: null,
      isDemoMode: false,
      activeDemoId: null,
      result: null,
      streamingText: '',
      isStreaming: true,
      streamStatus: '正在渲染 PDF 页面…',
      progressPercent: 0,
    });

    try {
      const response = await translatePdfAsImages({
        file,
        mode: state.mode,
        context: state.context || undefined,
        terminology: state.terminology || undefined,
        preserveNames: state.preserveNames,
        explainTranslation: state.explainTranslation,
      }, {
        signal: controller.signal,
        onProgress: ({ percent, status, provisionalText }) => {
          if (!isCurrent()) return;
          set({
            streamingText: provisionalText,
            streamStatus: visionStatusText(status, percent),
            progressPercent: percent,
          });
        },
      });

      if (!isCurrent()) return;
      set({
        result: toTranslationResult(response),
        isLoading: false,
        isStreaming: false,
        streamingText: '',
        streamStatus: null,
        progressPercent: 100,
        fileStatus: 'ready',
      });
    } catch (err) {
      if (!isCurrent()) return;
      set({
        isLoading: false,
        isStreaming: false,
        streamingText: '',
        streamStatus: null,
        progressPercent: null,
        error: err instanceof Error ? err.message : '逐页翻译失败，请稍后重试',
      });
    } finally {
      if (activeAbort === controller) activeAbort = null;
    }
  },
  
  // Full new-session reset (single implementation behind every "新建翻译"
  // entry). Clears the whole translation session: input, image, settings
  // (incl. anything a demo sample filled in), result/notes and demo state.
  // Deliberately KEEPS global app state: theme, service status.
  reset: () => {
    invalidateActiveStream();
    set({
      inputText: '',
      inputImage: null,
      imageSource: null,
      documentFile: null,
      fileStatus: 'idle',
      fileError: null,
      fileErrorCode: null,
      documentSourceFile: null,
      mode: 'auto',
      context: '',
      terminology: '',
      preserveNames: true,
      showTranslationNotes: false,
      result: null,
      error: null,
      isLoading: false,
      isDemoMode: false,
      activeDemoId: null,
      previewImage: null,
      isStreaming: false,
      streamingText: '',
      streamStatus: null,
      progressPercent: null,
    });
  }
}));
